growbox/home/routes.py
from datetime import datetime, timedelta

from flask import Blueprint, render_template, current_app
from flask_login import login_required
from sqlalchemy import desc, func

from growbox import create_app, db, mqtt
from growbox.models import Metric

home = Blueprint("home", __name__)
with create_app().app_context():
    topic_ctrl = current_app.config["MQTT_TOPIC_CTRL"]


@home.route('/dashboard/')
@login_required
def dashboard():
    return render_template("dashboard.html")


@home.route("/dashboard/now/")
@login_required
def dashboard_now():
    metric = Metric.query.order_by(desc(Metric.id)).first()
    return metric.as_dict()


@home.route("/dashboard/day/")
@login_required
def dashboard_day():
    date_start = datetime.utcnow() - timedelta(hours=2)
    date_end = datetime.utcnow()

    avg_dict = {}

    for i in range(12):
        curr_avg_tuple = db.session.query(func.avg(Metric.temperature_air),
                                          func.avg(Metric.temperature_ground),
                                          func.avg(Metric.humidity_air),
                                          func.avg(Metric.humidity_ground)) \
            .filter(date_start < Metric.date) \
            .filter(Metric.date < date_end) \
            .first()
        curr_avg_dict = {
            "date_start": date_start,
            "date_end": date_end,
            "temperature_air": curr_avg_tuple[0],
            "temperature_ground": curr_avg_tuple[1],
            "humidity_air": curr_avg_tuple[2],
            "humidity_ground": curr_avg_tuple[3]
        }

        avg_dict[i] = curr_avg_dict

        date_start = date_start - timedelta(hours=2)
        date_end = date_end - timedelta(hours=2)

    return avg_dict


@home.route("/dashboard/<string:time>/<int:amount>/", methods=["GET", "POST"])
@login_required
def dashboard_time(time, amount):
    before_time = datetime.utcnow() - timedelta(**{time: amount})
    metrics = Metric.query.filter(Metric.date >= before_time).all()
    result = {}
    for i, m in enumerate(metrics):
        result[i] = m.as_dict()
    return result


@home.route("/dashboard/led/<int:status>/", methods=["GET", "POST"])
@login_required
def toggle_led(status):
    if status == 1:
        mqtt.publish(topic_ctrl, "{\"LED\":\"on\"}")
    else:
        mqtt.publish(topic_ctrl, "{\"LED\":\"off\"}")
    return '', 200


@home.route("/dashboard/pump/<int:status>/", methods=["GET", "POST"])
@login_required
def toggle_pump(status):
    if status == 1:
        mqtt.publish(topic_ctrl, "{\"Pumpe\":\"on\"}")
    else:
        mqtt.publish(topic_ctrl, "{\"Pumpe\":\"off\"}")
    return '', 200


@home.route("/dashboard/heating/<int:status>/", methods=["GET", "POST"])
@login_required
def toggle_heating(status):
    if status == 1:
        mqtt.publish(topic_ctrl, "{\"Heizung\":\"on\"}")
    else:
        mqtt.publish(topic_ctrl, "{\"Heizung\":\"off\"}")
    return '', 200


@home.route("/dashboard/fan/<int:status>/", methods=["GET", "POST"])
@login_required
def toggle_fan(status):
    if status == 1:
        mqtt.publish(topic_ctrl, "{\"Luefter\":\"on\"}")
    else:
        mqtt.publish(topic_ctrl, "{\"Luefter\":\"off\"}")
    return '', 200

growbox/main/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user
from growbox import bcrypt
from growbox.main.forms import LoginForm
from growbox.models import User

main = Blueprint("main", __name__)

@main.route("/")
@main.route("/index/")
def index():
    if current_user.is_authenticated:
        return redirect(url_for("home.dashboard"))
    else:
        return redirect(url_for("main.login"))


@main.route("/login/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("home.dashboard"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for("home.dashboard"))
        else:
            flash(f"Login Unsuccessful. Please check username and password.", "danger")
    return render_template("login.html", form=form)


@main.route("/logout/")
def logout():
    logout_user()
    return redirect(url_for("main.index"))

growbox/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- jquery -->
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

        <!-- Bootstrap css -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">

        <!-- Custom css -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

        <!-- Chart.js -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js@3.2.0/dist/chart.min.js" integrity="sha256-ovnFmAOngtHmlhZzPyGrofexz4Kdik4kEobc8B9r1Yk=" crossorigin="anonymous"></script>

        <title>Growbox - {% block titel %}{% endblock %}</title>
    </head>
    <body>
        {% include 'header.html' %}

        {% block content %}{% endblock %}

        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    </body>
</html>

growbox/templates/dashboard.html
{% extends "base.html" %}
{% block titel %}Dashboard{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <main role="main" class="col-lg-12 px-4">

                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}

                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title text-center">Air Temperature <i
                                            class="bi bi-thermometer text-primary"></i></h5>
                                    <p id="temperature_air" class="metric card-text text-center">0</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title text-center">Soil Temperature <i
                                            class="bi bi-thermometer text-primary"></i></h5>
                                    <p id="temperature_ground" class="metric card-text text-center">0</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title text-center">Air Humidity <i
                                            class="bi bi-cloud-drizzle text-primary"></i></h5>
                                    <p id="humidity_air" class="metric card-text text-center">0</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title text-center">Soil Humidity <i
                                            class="bi bi-cloud-drizzle text-primary"></i></h5>
                                    <p id="humidity_ground" class="metric card-text text-center">0</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <hr>
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title card-title-switch">Light</h5>
                                    <div class="form-check form-switch switch-button">
                                        <input class="form-check-input" type="checkbox"
                                               id="flex_switch_light"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title card-title-switch">Pump</h5>
                                    <div class="form-check form-switch switch-button">
                                        <input class="form-check-input" type="checkbox"
                                               id="flex_switch_pump"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title card-title-switch">Heating</h5>
                                    <div class="form-check form-switch switch-button">
                                        <input class="form-check-input" type="checkbox"
                                               id="flex_switch_heating"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title card-title-switch">Fan</h5>
                                    <div class="form-check form-switch switch-button">
                                        <input class="form-check-input" type="checkbox"
                                               id="flex_switch_fan"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <hr>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title text-center">Temperature</h5>
                                    <canvas id="temperatureChart"></canvas>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title text-center">Humidity</h5>
                                    <canvas id="humidityChart"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </main>
        </div>
    </div>
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-3">
                <button type="button" class="btn btn-primary" id="speech-rec">Speech Recognition</button>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{{ url_for('static', filename='dashboard.js') }}"></script>

{% endblock %}

growbox/templates/header.html
<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand col-lg-2 col-md-3" href="{{ url_for('main.index') }}">Growbox</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('home.dashboard') }}">Dashboard</a>
                {% endif %}
            </div>
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

growbox/templates/login.html
{% extends "base.html" %}
{% block titel %}Login{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <main role="main" class="col-sm-8 col-md-6 col-lg-4 col-centered">

                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}

                <form method="POST" action="">
                    {{ form.hidden_tag() }} <!-- generates a hidden field that includes a token that is used to protect the form against CSRF attacks -->
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Login</legend>
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label") }}
        
                            {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="form-control-label") }}
                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-check">
                            {{ form.remember(class="form-check-input") }}
                            {{ form.remember.label(class="form-check-label") }}
                        </div>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>


{% endblock %}